//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrispyKreme.KrispyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidaCupon", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ValidaCupon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeValidacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValidaCuponIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeValidacion {
            get {
                return this.MensajeValidacionField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeValidacionField, value) != true)) {
                    this.MensajeValidacionField = value;
                    this.RaisePropertyChanged("MensajeValidacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ValidaCuponID {
            get {
                return this.ValidaCuponIDField;
            }
            set {
                if ((this.ValidaCuponIDField.Equals(value) != true)) {
                    this.ValidaCuponIDField = value;
                    this.RaisePropertyChanged("ValidaCuponID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KrispyService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidarCupon", ReplyAction="http://tempuri.org/IService/ValidarCuponResponse")]
        KrispyKreme.KrispyService.ValidaCupon ValidarCupon(int idCupon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidarCupon", ReplyAction="http://tempuri.org/IService/ValidarCuponResponse")]
        System.Threading.Tasks.Task<KrispyKreme.KrispyService.ValidaCupon> ValidarCuponAsync(int idCupon);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : KrispyKreme.KrispyService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<KrispyKreme.KrispyService.IService>, KrispyKreme.KrispyService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KrispyKreme.KrispyService.ValidaCupon ValidarCupon(int idCupon) {
            return base.Channel.ValidarCupon(idCupon);
        }
        
        public System.Threading.Tasks.Task<KrispyKreme.KrispyService.ValidaCupon> ValidarCuponAsync(int idCupon) {
            return base.Channel.ValidarCuponAsync(idCupon);
        }
    }
}
